lock_axes: false
vmin_db: -120.0
video_path: D:\Alice\VidData\20250309_01_Ivy\2025-03-09_013_Ivy-cam-2.mp4
recompute_threshold: 0.5
video_folder: D:/Alice/VidData/20250309_01_Ivy
hop_frac: 0.5
fps_playback: 100.0
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
vmax_db: 20.0
window_size: 5.0
ymax: 100.0
buffer_multiplier: 5.0
space_plot_type: Layer controls
ymin: 0.0
video_buffer_size: 300
plot_spectrogram: false
cmap: magma
nfft: 1024
cameras_sel: cam2_files
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: position
individuals_sel: Ivy
individuals_sel_previous: Poppy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
trial_conditions_sel: None
trials_sel: 13
