recompute_threshold: 0.5
window_size: 3.0
jump_size: 0.2
buffer_multiplier: 5.0
fps_playback: 100.0
plot_spectrogram: false
ymin: 0.0
nfft: 1024
cmap: magma
video_buffer_size: 300
file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-03_id-Freddy/ses-000_date-20250527_01/behav/Trial_data.nc
hop_frac: 0.5
sync_state: lineplot_to_video
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250527_01_Freddy
vmax_db: 20.0
vmin_db: -120.0
ymax: 120.0
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250527_01_Freddy\2025-05-27_001_Freddy-cam-1.mp4
cameras_sel: cam1_files
colors_sel: angle_rgb
features_sel: speed
individuals_sel: Freddy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
