vmin_db: -120.0
space_plot_type: plot_box_topview
fps_playback: 100.0
video_buffer_size: 300
ymax: 100
hop_frac: 0.5
lock_axes: false
window_size: 1.350400286241463
vmax_db: 20.0
recompute_threshold: 0.5
plot_spectrogram: false
buffer_multiplier: 5.0
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
video_folder: D:/Alice/VidData/20250309_01_Ivy
ymin: 0
video_path: D:\Alice\VidData\20250309_01_Ivy\2025-03-09_013_Ivy-cam-2.mp4
cmap: magma
nfft: 1024
cameras_sel: cam2_files
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
individuals_sel_previous: Freddy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
trial_conditions_sel: None
trials_sel: 13
