window_size: 3.0
buffer_multiplier: 5.0
ymin: 0.0
cmap: magma
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250527_01_Freddy
file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-03_id-Freddy/ses-000_date-20250527_01/behav/Trial_data.nc
plot_spectrogram: false
vmax_db: 20.0
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250527_01_Freddy\2025-05-27_001_Freddy-cam-1.mp4
nfft: 1024
ymax: 120.0
sync_state: video_to_lineplot
video_buffer_size: 300
recompute_threshold: 0.5
fps_playback: 100.0
hop_frac: 0.5
vmin_db: -120.0
jump_size: 0.2
cameras_sel: cam1_files
colors_sel: angle_rgb
features_sel: speed
individuals_sel: Freddy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
