nfft: 1024
buffer_multiplier: 5.0
recompute_threshold: 0.5
fps_playback: 100.0
video_path: D:\Alice\VidData\20250309_01_Ivy\2025-03-09_013_Ivy-cam-2.mp4
video_folder: D:/Alice/VidData/20250309_01_Ivy
lock_axes: false
cmap: magma
space_plot_type: Layer controls
window_size: 5.0
ymin: 0.0
hop_frac: 0.5
plot_spectrogram: false
vmin_db: -120.0
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
video_buffer_size: 300
vmax_db: 20.0
ymax: 100.0
cameras_sel: cam2_files
colors_sel: angle_rgb
features_sel: position
features_sel_previous: speed
individuals_sel: Ivy
individuals_sel_previous: Poppy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
trial_conditions_sel: None
trials_sel: 13
