spec_buffer: 3.0
cmap: magma
video_path: C:\Users\Admin\Documents\Akseli\bird\bird.mp4
audio_folder: C:/Users/Admin/Documents/Akseli/bird
sync_state: lineplot_to_video
plot_spectrogram: true
audio_path: C:\Users\Admin\Documents\Akseli\bird\bird.wav
ymin: -0.06463014199431966
window_size: 1.4377300913957283
vmax_db: 20.0
buffer_multiplier: 5.0
fps_playback: 30.0
ymax: 0.48447416183191055
file_path: C:/Users/Admin/Documents/Akseli/bird/bird.nc
audio_buffer: 0.5
video_folder: C:/Users/Admin/Documents/Akseli/bird
nfft: 1024
vmin_db: -120.0
jump_size: 0.2
video_buffer_size: 300
hop_frac: 0.5
recompute_threshold: 0.5
cameras_sel: cam1_files
features_sel: envelope
individuals_sel: Blue bird
mics_sel: mic1_files
trials_sel: 1
