video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250527_01_Freddy
file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-03_id-Freddy/ses-000_date-20250527_01/behav/Trial_data.nc
fps_playback: 100.0
jump_size: 0.2
ymax: 52.768950000000004
ymin: -4.872050000000001
window_size: 2.973
audio_folder: C:/Users/Admin/Downloads/sample-15s.wav
cameras_sel: cam2_files
colors_sel: angle_rgb
features_sel: speed
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
