recompute_threshold: 0.5
fps_playback: 200.0
plot_spectrogram: false
vmin_db: -120.0
buffer_multiplier: 5.0
cmap: magma
vmax_db: 20.0
ymin: 0.0
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
video_path: D:\Alice\VidData\20250309_01_Ivy\2025-03-09_001_Ivy-cam-2.mp4
ymax: 150.0
video_folder: D:/Alice/VidData/20250309_01_Ivy
window_size: 3.0
video_buffer_size: 300
hop_frac: 0.5
nfft: 1024
cameras_sel: cam2_files
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: position
individuals_sel: Ivy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
