vmax_db: 20.0
ymin: 0.0
nfft: 1024
nc_file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
vmin_db: -120.0
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250309_01_Ivy\2025-03-09_001_Ivy-cam-1.mp4
buffer_multiplier: 5.0
jump_size: 0.2
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250309_01_Ivy
ymax: 120.0
hop_frac: 0.5
cmap: magma
plot_spectrogram: false
window_size: 2.0
recompute_threshold: 0.5
sync_state: lineplot_to_video
fps_playback: 50.0
video_buffer_size: 300
cameras_sel: cam1_files
colors_sel: angle_rgb
features_sel: speed
individuals_sel: Ivy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
