video_folder: C:/Users/Admin/Documents/Akseli/bird
vmax_db: 20.0
file_path: C:/Users/Admin/Documents/Akseli/bird/bird.nc
window_size: 536.4694337407868
sync_state: lineplot_to_video
vmin_db: -120.0
audio_buffer: 0.5
jump_size: 0.2
video_path: C:\Users\Admin\Documents\Akseli\bird\bird.mp4
fps_playback: 30.0
ymin: -0.03315912741151335
hop_frac: 0.5
buffer_multiplier: 5.0
audio_path: C:\Users\Admin\Documents\Akseli\bird\bird.wav
audio_volume: 100
nfft: 1024
cmap: magma
video_buffer_size: 300
audio_folder: C:/Users/Admin/Documents/Akseli/bird
ymax: 0.4417210787888143
recompute_threshold: 0.5
plot_spectrogram: false
spec_buffer: 3.0
cameras_sel: cam1_files
features_sel: envelope
individuals_sel: Blue bird
mics_sel: mic1_files
trials_sel: 1
