recompute_threshold: 0.5
nfft: 1024
video_buffer_size: 300
buffer_multiplier: 5.0
fps_playback: 30.0
sync_state: video_to_lineplot
video_path: C:\Users\aksel\Documents\Code\caltech\PAIR-R24M-Dataset\20210119_Recording_SR1_SR2_social_vidtwo\videos\Camera4\0.mp4
nc_file_path: C:/Users/aksel/Documents/Code/caltech/data.nc
vmin_db: -120.0
window_size: 2.0
video_folder: C:/Users/aksel/Documents/Code/caltech/PAIR-R24M-Dataset/20210119_Recording_SR1_SR2_social_vidtwo/videos
hop_frac: 0.5
vmax_db: 20.0
plot_spectrogram: false
cmap: magma
jump_size: 0.2
cameras_sel: cam-4
features_sel: velocity
individuals_sel: an2
keypoints_sel: HeadB
tracking_sel: dlc1_files
trials_sel: 0
