jump_size: 0.2
window_size: 4.138932554202834
spec_ymin: 166.78532147741544
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250527_01_Freddy
file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-03_id-Freddy/ses-000_date-20250527_01/behav/Trial_data.nc
ymin: -6.436455229488528
fps_playback: 100.0
ymax: 157.22232964270404
plot_spectrogram: 0.0
spec_ymax: 21883.21467852258
audio_folder: C:/Users/Admin/Downloads/sample-15s.wav
cameras_sel: cam1_files
colors_sel: angle_rgb
features_sel: speed
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
