percentile_ylim: 99.5
video_path: C:\Users\Admin\Documents\Akseli\sample_data\eye\video1.mp4
video_buffer_size: 300
video_folder: C:/Users/Admin/Documents/Akseli/sample_data/eye
nfft: 1024
recompute_threshold: 0.5
tracking_folder: C:/Users/Admin/Documents/Akseli/sample_data/eye
vmin_db: -120.0
nc_file_path: C:/Users/Admin/Documents/Akseli/sample_data/eye/dlc_eye_tracking.nc
hop_frac: 0.5
buffer_multiplier: 5.0
window_size: 2.0
space_plot_type: plot_centroid_trajectory
cmap: magma
plot_spectrogram: false
fps_playback: 10.0
lock_axes: false
vmax_db: 20.0
cameras_sel: cam1
features_sel: position_norm
features_sel_previous: position
individuals_sel: individual_0
keypoints_sel: pupil-L
keypoints_sel_previous: pupil-R
tracking_sel: dlc1
trials_sel: 0
