fps_playback: 200.0
video_path: D:\Alice\VidData\20250309_01_Ivy\2025-03-09_002_Ivy-cam-2.mp4
vmin_db: -120.0
cmap: magma
plot_spectrogram: false
recompute_threshold: 0.5
video_buffer_size: 300
video_folder: D:/Alice/VidData/20250309_01_Ivy
nfft: 1024
hop_frac: 0.5
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
ymax: 100.0
ymin: -5.0
vmax_db: 20.0
buffer_multiplier: 5.0
window_size: 3.0
cameras_sel: cam2_files
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: position
individuals_sel: Ivy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 2
