file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-03_id-Freddy/ses-000_date-20250527_01/behav/Trial_data.nc
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250527_01_Freddy
buffer_multiplier: 5.0
window_size: 3.0
sync_state: lineplot_to_video
video_buffer_size: 300
jump_size: 0.2
cmap: magma
plot_spectrogram: false
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250527_01_Freddy\2025-05-27_001_Freddy-cam-1.mp4
recompute_threshold: 0.5
nfft: 1024
hop_frac: 0.5
vmax_db: 20.0
ymax: 150.0
vmin_db: -120.0
ymin: 0.0
cameras_sel: cam1_files
colors_sel: angle_rgb
features_sel: speed
individuals_sel: Freddy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
