file_path: C:/Users/Admin/Documents/Akseli/bird/bird.nc
jump_size: 0.2
plot_spectrogram: false
audio_folder: C:/Users/Admin/Documents/Akseli/bird
video_path: C:\Users\Admin\Documents\Akseli\bird\bird.mp4
recompute_threshold: 0.5
vmin_db: -120.0
ymax: 0.2
sync_state: lineplot_to_video
cmap: magma
video_buffer_size: 300
audio_path: C:\Users\Admin\Documents\Akseli\bird\bird.wav
video_folder: C:/Users/Admin/Documents/Akseli/bird
buffer_multiplier: 5.0
fps_playback: 30.0
window_size: 2.0
nfft: 1024
ymin: 0.0
vmax_db: 20.0
hop_frac: 0.5
cameras_sel: cam1_files
features_sel: envelope
individuals_sel: Green bird
mics_sel: mic1_files
trials_sel: 1
