plot_spectrogram: false
hop_frac: 0.5
fps_playback: 30.0
video_buffer_size: 300
buffer_multiplier: 5.0
vmax_db: 20.0
percentile_ylim: 99.9
ymin: 0.0
vmin_db: -120.0
ymax: 50.0
space_plot_type: Layer controls
recompute_threshold: 0.5
window_size: 2.0
video_path: D:\Alice\VidData\20250527_01_Freddy\2025-05-27_008_Freddy-cam-1.mp4
nfft: 1024
nc_file_path: D:/Alice/AK_data/derivatives/sub-03_id-Freddy/ses-000_date-20250527_01/behav/Trial_data.nc
cmap: magma
video_folder: D:/Alice/VidData/20250527_01_Freddy
cameras_sel: cam1_file
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Freddy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
tracking_sel: dlc1_file
trial_conditions_sel: None
trials_sel: 8
