video_folder: D:/Alice/VidData/20250309_01_Ivy
nfft: 1024
buffer_multiplier: 5.0
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
vmax_db: 20.0
video_buffer_size: 300
ymin: 0.0
recompute_threshold: 0.5
plot_spectrogram: false
hop_frac: 0.5
ymax: 150.0
vmin_db: -120.0
fps_playback: 30.0
cmap: magma
video_path: D:\Alice\VidData\20250309_01_Ivy\2025-03-09_002_Ivy-cam-2.mp4
window_size: 3.0
cameras_sel: cam2_files
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: position
individuals_sel: Ivy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 2
