jump_size: 0.2
video_buffer_size: 300
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250309_01_Ivy
vmin_db: -120.0
fps_playback: 50.0
plot_spectrogram: false
hop_frac: 0.5
ymin: 0.0
buffer_multiplier: 5.0
sync_state: lineplot_to_video
cmap: magma
ymax: 120.0
vmax_db: 20.0
window_size: 2.0
nc_file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
nfft: 1024
recompute_threshold: 0.5
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250309_01_Ivy\2025-03-09_001_Ivy-cam-1.mp4
cameras_sel: cam1_files
colors_sel: angle_rgb
features_sel: velocity
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
