plot_spectrogram: false
nfft: 1024
nc_file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
buffer_multiplier: 5.0
cmap: magma
hop_frac: 0.5
video_buffer_size: 300
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250309_01_Ivy\2025-03-09_001_Ivy-cam-1.mp4
window_size: 2.0
recompute_threshold: 0.5
jump_size: 0.2
vmin_db: -120.0
fps_playback: 50.0
ymax: 150.0
ymin: 0.0
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250309_01_Ivy
vmax_db: 20.0
cameras_sel: cam1_files
colors_sel: angle_rgb
features_sel: speed
individuals_sel: Ivy
keypoints_sel: beakTip
trial_conditions_sel: None
trials_sel: 1
