audio_folder: C:/Users/aksel/Documents/Code/movformer-gui/downloads
nc_file_path: C:/Users/aksel/Documents/Code/movformer-gui/downloads/hands.nc
plot_spectrogram: false
buffer_multiplier: 5.0
tracking_folder: C:/Users/aksel/Documents/Code/movformer-gui/downloads
recompute_threshold: 0.5
video_folder: C:/Users/aksel/Documents/Code/movformer-gui/downloads
video_buffer_size: 300
fps_playback: 30.0
cmap: magma
window_size: 2.0
vmin_db: -120.0
space_plot_type: Layer controls
vmax_db: 20.0
percentile_ylim: 99.5
nfft: 1024
hop_frac: 0.5
