file_path: C:/Users/Admin/Documents/Akseli/AI_data/derivatives/sub-02_id-Poppy/ses-000_date-20250901_01/behav/Trial_data.nc
video_buffer_size: 300
video_folder: C:/Users/Admin/Documents/Akseli/VidData/20250901_01_Poppy
nfft: 1024
tracking_folder: C:/Users/Admin/Documents/Akseli/AI_data/rawdata/sub-02_id-Poppy/ses-000_date-20250901_01/behav/dlc
vmin_db: -120.0
fps_playback: 30.0
recompute_threshold: 0.5
hop_frac: 0.5
window_size: 2.0
cmap: magma
video_path: C:\Users\Admin\Documents\Akseli\VidData\20250901_01_Poppy\2025-09-01_001_Poppy-cam-1.mp4
sync_state: video_to_lineplot
buffer_multiplier: 5.0
plot_spectrogram: false
jump_size: 0.2
vmax_db: 20.0
DeepLabCut_sel: dlc1_files
cameras_sel: cam1_files
features_sel: speed
individuals_sel: Poppy
keypoints_sel: beakTip
tracking_sel: dlc1_files
trials_sel: 0
