ymax: 100.0
vmin_db: -120.0
fps_playback: 100.0
lock_axes: true
video_path: D:\Alice\VidData\20250309_01_Ivy\2025-03-09_008_Ivy-cam-2.mp4
buffer_multiplier: 5.0
cmap: magma
hop_frac: 0.5
video_folder: D:/Alice/VidData/20250309_01_Ivy
recompute_threshold: 0.5
video_buffer_size: 300
space_plot_type: Layer controls
window_size: 2.0
nc_file_path: D:/Alice/AK_data/derivatives/sub-01_id-Ivy/ses-000_date-20250309_01/behav/Trial_data.nc
nfft: 1024
ymin: 0.0
plot_spectrogram: false
vmax_db: 20.0
cameras_sel: cam2_files
colors_sel: angle_rgb
features_sel: speed
features_sel_previous: velocity
individuals_sel: Ivy
individuals_sel_previous: Poppy
keypoints_sel: beakTip
keypoints_sel_previous: stickTip
trial_conditions_sel: None
trials_sel: 8
